### ISSUE TITLE
Kitchen Sink?

### ISSUE THREAD

**Issue by mitchngwen** [KingDan27/Industrial-Architecture-2.0#1]
This is not a Kitchen Sink pack the description was misleading. Recipes are highly altered making this not a kitchen sink pack.

**Comment by KingDan27** [comment]
You are absolutely correct this was a mistake on my end, I had copied and pasted from my original IA modpacks description and forgot to update the discription before i put it into Beta/Release. As I have updated the discription this issue will be closed. Thanks for reporting.
